apiVersion: v1
kind: Secret
metadata:
  name: secret-example
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "QllVQjdMQUcwU1hMT0NHS0lCWUc=" # your key or user name (base64 encoded)
  AWS_SECRET_ACCESS_KEY: "ZHFCWFRUUEs2c3U4TlFXY29XUzk2dURpREVGU0V0TnlwRTAzRDMxVQ==" # your secret or password (base64 encoded)
