apiVersion: hypercloud.tmaxanc.com/v1alpha1
kind: VirtualMachineImage
metadata:
  name: myubuntu
spec:
  source:
    # qcow2 이미지의 http 경로
    http: https://download.cirros-cloud.net/contrib/0.3.0/cirros-0.3.0-i386-disk.img
  # 스냅샷 프로비저닝을 위해 사용 할 CSI를 담은 객체(snapshotClass)의 이름
  snapshotClassName: csi-rbdplugin-snapclass
  pvc:
    # VirtualMachineImage 생성 시 volumeMode는 필수 값이고 Block만 가능
    volumeMode: Block
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "3Gi"
    storageClassName: rook-ceph-block
