apiVersion: hypercloud.tmaxanc.com/v1alpha1
kind: VirtualMachineImage
metadata:
  name: localvmim
spec:
  source:
    hostPath:
      path: /mnt/hy
      nodeName: young
  snapshotClassName: csi-rbdplugin-snapclass
  pvc:
    volumeMode: Block
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: "3Gi"
    storageClassName: rook-ceph-block
