apiVersion: hypercloud.tmaxanc.com/v1alpha1
kind: VirtualMachineVolumeExport
metadata:
  name: s3-export
spec:
  virtualMachineVolume:
    name: myrootdisk
  destination:
    s3:
      # s3 endpoint with bucket and object name in virtual hosted style, https://bucketname.s3.region.amazonaws.com/objectkeyname
      url: "http://ceph-bucket.rook-ceph-rgw-my-store.rook-ceph:80/disk.img"
      # the name of secret which contains accessKeyID and secretAccessKey of the s3 endpoint
      secretRef: secret-example
