apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualmachinevolumeexports.hypercloud.tmaxanc.com
spec:
  group: hypercloud.tmaxanc.com
  names:
    kind: VirtualMachineVolumeExport
    listKind: VirtualMachineVolumeExportList
    plural: virtualmachinevolumeexports
    shortNames:
    - vmve
    singular: virtualmachinevolumeexport
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current state of VirtualMachineVolumeExport
      jsonPath: .status.state
      name: State
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: VirtualMachineVolumeExport is the Schema for the virtualmachinevolumeexports
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VirtualMachineVolumeExportSpec defines the desired state
              of VirtualMachineVolumeExport
            properties:
              destination:
                description: VirtualMachineVolumeExportDestination defines the destination
                  to export volume
                properties:
                  local:
                    description: VirtualMachineVolumeExportDestinationLocal defines
                      the Local destination to export volume
                    type: object
                  s3:
                    description: VirtualMachineVolumeExportDestinationS3 defines a
                      s3 destination to export a volume
                    properties:
                      secretRef:
                        description: SecretRef is the secret reference which is needed
                          to access the S3 endpoint
                        type: string
                      url:
                        description: Url is the S3 endpoint
                        type: string
                    required:
                    - url
                    type: object
                type: object
              virtualMachineVolume:
                description: VirtualMachineVolumeSource indicates the VirtualMachineVolume
                  to be exported
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
            required:
            - destination
            - virtualMachineVolume
            type: object
          status:
            description: VirtualMachineVolumeExportStatus defines the observed state
              of VirtualMachineVolumeExport
            properties:
              conditions:
                description: Conditions indicate current conditions of VirtualMachineVolumeExport
                items:
                  description: Condition indicates observed condition of an object
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              state:
                description: State is the current state of VirtualMachineVolumeExport
                type: string
            required:
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
