kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevirt-image-service
subjects:
- kind: ServiceAccount
  name: kubevirt-image-service
  namespace: kis
roleRef:
  kind: ClusterRole
  name: kubevirt-image-service
  apiGroup: rbac.authorization.k8s.io

